<nav class="nav">
<a <?php echo($page=="companypage")?"class='active'":""; ?> href="index.php">Company</a>
<a <?php echo($page=="jobspage")?"class='active'":""; ?> href="job.php">Jobs</a>
<a <?php echo($page=="applypage")?"class='active'":""; ?> href="apply.php">Apply</a>
<a <?php echo($page=="aboutpage")?"class='active'":""; ?> href="about.php">Details</a>
<a <?php echo($page=="managepage")?"class='active'":""; ?> href="login.php">Manage</a>
<a <?php echo($page=="enhancementspage")?"class='active'":""; ?> href="enhancements.php">E1</a>
<a <?php echo($page=="phpenhancementspage")?"class='active'":""; ?> href="phpenhancements.php">E3</a>
</nav>

 <hr id="hr"/>
</header>